# Generated by Django 4.0.2 on 2022-02-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('tester_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('test_id', models.IntegerField()),
                ('time', models.CharField(max_length=200)),
                ('phone_manufacturer', models.CharField(max_length=200)),
                ('phone_model', models.CharField(max_length=200)),
                ('screen_height', models.CharField(max_length=200)),
                ('screen_width', models.CharField(max_length=200)),
                ('video_file', models.FileField(default='testdef', upload_to='')),
            ],
        ),
    ]
